name: Quality checks
on: push

jobs:
  check_quality:
    name: Several quality checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: grep "Tsitsi Dalakishvili" README.md
